=== testleaftrainings/RestAPI_Oct_2025/rest-api-session-oct-2025/src/main/resources/schema/fakeapi-get-activities.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "array",
  "items" : {
    "type" : "object",
    "properties" : {
      "completed" : {
        "type" : "boolean"
      },
      "dueDate" : {
        "type" : "string"
      },
      "id" : {
        "type" : "integer"
      },
      "title" : {
        "type" : "string"
      }
    }
  }
}

=== testleaftrainings/RestAPI_Oct_2025/rest-api-session-oct-2025/src/main/resources/FakeRESTApi/get-activities.json
[
  {
    "id": 1,
    "title": "Activity 1",
    "dueDate": "2025-12-13T10:41:07.3104817+00:00",
    "completed": false
  },
  {
    "id": 2,
    "title": "Activity 2",
    "dueDate": "2025-12-13T11:41:07.3104841+00:00",
    "completed": true
  },
  {
    "id": 3,
    "title": "Activity 3",
    "dueDate": "2025-12-13T12:41:07.3104846+00:00",
    "completed": false
  },
  {
    "id": 4,
    "title": "Activity 4",
    "dueDate": "2025-12-13T13:41:07.3104849+00:00",
    "completed": true
  },
  {
    "id": 5,
    "title": "Activity 5",
    "dueDate": "2025-12-13T14:41:07.3104852+00:00",
    "completed": false
  },
  {
    "id": 6,
    "title": "Activity 6",
    "dueDate": "2025-12-13T15:41:07.3104858+00:00",
    "completed": true
  },
  {
    "id": 7,
    "title": "Activity 7",
    "dueDate": "2025-12-13T16:41:07.3104861+00:00",
    "completed": false
  },
  {
    "id": 8,
    "title": "Activity 8",
    "dueDate": "2025-12-13T17:41:07.3104864+00:00",
    "completed": true
  },
  {
    "id": 9,
    "title": "Activity 9",
    "dueDate": "2025-12-13T18:41:07.3104867+00:00",
    "completed": false
  },
  {
    "id": 10,
    "title": "Activity 10",
    "dueDate": "2025-12-13T19:41:07.3104872+00:00",
    "completed": true
  },
  {
    "id": 11,
    "title": "Activity 11",
    "dueDate": "2025-12-13T20:41:07.3104876+00:00",
    "completed": false
  },
  {
    "id": 12,
    "title": "Activity 12",
    "dueDate": "2025-12-13T21:41:07.3104879+00:00",
    "completed": true
  },
  {
    "id": 13,
    "title": "Activity 13",
    "dueDate": "2025-12-13T22:41:07.3104882+00:00",
    "completed": false
  },
  {
    "id": 14,
    "title": "Activity 14",
    "dueDate": "2025-12-13T23:41:07.3104885+00:00",
    "completed": true
  },
  {
    "id": 15,
    "title": "Activity 15",
    "dueDate": "2025-12-14T00:41:07.3104888+00:00",
    "completed": false
  },
  {
    "id": 16,
    "title": "Activity 16",
    "dueDate": "2025-12-14T01:41:07.3104891+00:00",
    "completed": true
  },
  {
    "id": 17,
    "title": "Activity 17",
    "dueDate": "2025-12-14T02:41:07.3104894+00:00",
    "completed": false
  },
  {
    "id": 18,
    "title": "Activity 18",
    "dueDate": "2025-12-14T03:41:07.3104898+00:00",
    "completed": true
  },
  {
    "id": 19,
    "title": "Activity 19",
    "dueDate": "2025-12-14T04:41:07.3104901+00:00",
    "completed": false
  },
  {
    "id": 20,
    "title": "Activity 20",
    "dueDate": "2025-12-14T05:41:07.3104905+00:00",
    "completed": true
  },
  {
    "id": 21,
    "title": "Activity 21",
    "dueDate": "2025-12-14T06:41:07.3104908+00:00",
    "completed": false
  },
  {
    "id": 22,
    "title": "Activity 22",
    "dueDate": "2025-12-14T07:41:07.3104911+00:00",
    "completed": true
  },
  {
    "id": 23,
    "title": "Activity 23",
    "dueDate": "2025-12-14T08:41:07.3104915+00:00",
    "completed": false
  },
  {
    "id": 24,
    "title": "Activity 24",
    "dueDate": "2025-12-14T09:41:07.3104918+00:00",
    "completed": true
  },
  {
    "id": 25,
    "title": "Activity 25",
    "dueDate": "2025-12-14T10:41:07.3104921+00:00",
    "completed": false
  },
  {
    "id": 26,
    "title": "Activity 26",
    "dueDate": "2025-12-14T11:41:07.3104924+00:00",
    "completed": true
  },
  {
    "id": 27,
    "title": "Activity 27",
    "dueDate": "2025-12-14T12:41:07.3104926+00:00",
    "completed": false
  },
  {
    "id": 28,
    "title": "Activity 28",
    "dueDate": "2025-12-14T13:41:07.3104929+00:00",
    "completed": true
  },
  {
    "id": 29,
    "title": "Activity 29",
    "dueDate": "2025-12-14T14:41:07.3104932+00:00",
    "completed": false
  },
  {
    "id": 30,
    "title": "Activity 30",
    "dueDate": "2025-12-14T15:41:07.3104935+00:00",
    "completed": true
  }
]
